/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminHtmlNestedRouteImport } from './routes/admin/html'
import { Route as AdminHtmlRouteImport } from './routes/admin.html'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as IndexRouteImport } from './routes/index'

const AdminHtmlNestedRoute = AdminHtmlNestedRouteImport.update({
  id: '/admin/html',
  path: '/admin/html',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHtmlRoute = AdminHtmlRouteImport.update({
  id: '/admin.html',
  path: '/admin.html',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/html': typeof AdminHtmlNestedRoute
  '/admin.html': typeof AdminHtmlRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/html': typeof AdminHtmlNestedRoute
  '/admin.html': typeof AdminHtmlRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/html': typeof AdminHtmlNestedRoute
  '/admin.html': typeof AdminHtmlRoute
  '/stats': typeof StatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/html' | '/admin.html' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/html' | '/admin.html' | '/stats'
  id: '__root__' | '/' | '/admin/html' | '/admin.html' | '/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminHtmlNestedRoute: typeof AdminHtmlNestedRoute
  AdminHtmlRoute: typeof AdminHtmlRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/html': {
      id: '/admin/html'
      path: '/admin/html'
      fullPath: '/admin/html'
      preLoaderRoute: typeof AdminHtmlNestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin.html': {
      id: '/admin.html'
      path: '/admin.html'
      fullPath: '/admin.html'
      preLoaderRoute: typeof AdminHtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminHtmlNestedRoute: AdminHtmlNestedRoute,
  AdminHtmlRoute: AdminHtmlRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
